/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-09 03:58:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hotelInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/template/footer.jsp", Long.valueOf(1667795532121L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654647991285L));
    _jspx_dependants.put("jar:file:/C:/sevenfactory/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/sevenfactory_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 동적인 페이지 포함 -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/template/header.jsp", out, false);
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=6f3e6622db3f5814e8e191da89d96838&libraries=LIBRARY\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\" >\n");
      out.write("	* {\n");
      out.write("		font-family: \"Inconsolata\", sans-serif;\n");
      out.write("	}\n");
      out.write("	.bgimg { \n");
      out.write("		background-position: center;\n");
      out.write("		background-size: cover;\n");
      out.write("		background-image: url(\"resources/assets/aboutUs_img/hotel.jpg\");\n");
      out.write("		min-height: 750px;\n");
      out.write("	}\n");
      out.write("	#map{\n");
      out.write("		margin: 0 auto;\n");
      out.write("	}\n");
      out.write("	table {\n");
      out.write("		border-collapse: collapse;\n");
      out.write("		width: 55%;\n");
      out.write("		margin: 0 auto;\n");
      out.write("		margin-top: 30px;\n");
      out.write("		margin-bottom: 30px;\n");
      out.write("	}\n");
      out.write("	th, td {\n");
      out.write("		padding: 8px;\n");
      out.write("		text-align: left;\n");
      out.write("		border-bottom: 1px solid #ddd;\n");
      out.write("	}\n");
      out.write("	tr:hover {background-color:#f5f5f5;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<header class=\"bgimg w3-display-container w3-grayscale-min\" id=\"home\">\n");
      out.write("	<div class=\"w3-display-bottomleft w3-center w3-padding-large w3-hide-small\">\n");
      out.write("		<span class=\"w3-tag\">A Global Leading</span>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"w3-display-middle w3-center\">\n");
      out.write("		<span class=\"w3-text-white\" style=\"font-size:90px\">Together</span>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"w3-display-bottomright w3-center w3-padding-large\">\n");
      out.write("		<span class=\"w3-text-white\">Your Lifetime Friend</span>\n");
      out.write("	</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- About Container -->\n");
      out.write("<div class=\"w3-container\" id=\"about\">\n");
      out.write("	<div class=\"w3-content\" style=\"max-width:700px\">\n");
      out.write("		<h5 class=\"w3-center w3-padding-64\"><span class=\"w3-tag w3-wide\">ABOUT THE US</span></h5>\n");
      out.write("		<p>투게더(Together)는 대한민국 최대규모 반려견 동반 호텔 예약 사이트입니다. 이제 아시아를 넘어 세계로 뻗어가는 글로벌 호텔로서 전세계 어디에서나 한결같이 품격있는 서비스와 시설로 고객에게 깊은 감동을 주는 브랜드를 지향하고 있습니다. <br/><br/>균형 있는 라이프스타일을 추구하며 품격의 가치를 아는 고객을 위해 세련되고 모던한 감각을 지닌 안락한 객실과 세심한 배려가 묻어나는 서비스를 준비합니다. 또한 투게더만의 감각적인 뷰와 다양한 경험을 제공하는 호텔시설은 감동을 더해드립니다.</p>\n");
      out.write("		<p>투게더에서 품격 있는 휴식으로 삶의 균형을 완성해가시길 바랍니다.</p>\n");
      out.write("		<div class=\"w3-panel w3-leftbar w3-light-grey\">\n");
      out.write("			<p><i>\"고객으로부터 신뢰받는 프로로서의 자부심과 열정을 잊지 않는다\" -사랑, 자유, 풍요의 꿈을 실현하는 투게더의 철학</i></p>\n");
      out.write("			<p>고품격 경영 업계 선도</p>\n");
      out.write("		</div>\n");
      out.write("<img src=\"resources/assets/aboutUs_img/room.jpg\" style=\"width:100%;max-width:1000px\" class=\"w3-margin-top\">\n");
      out.write("<p><strong>Tel : </strong>010-1111-1111</p>\n");
      out.write("<p><strong>Email : </strong>admin@google.com</p>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<h5 class=\"w3-center w3-padding-48\"><span class=\"w3-tag w3-wide\">WHERE TO FIND US</span></h5>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	// 이미지 지도에 표시할 마커입니다\n");
      out.write("	// 이미지 지도에 표시할 마커를 아래와 같이 배열로 넣어주면 여러개의 마커를 표시할 수 있습니다 \n");
      out.write("		var mapContainer = document.getElementById('map'), // 지도를 표시할 div \n");
      out.write("		mapOption = { \n");
      out.write("		        center: new kakao.maps.LatLng(36.349268551597966 , 127.37767658950676), // 지도의 중심좌표\n");
      out.write("		        level: 3 // 지도의 확대 레벨\n");
      out.write("		    };\n");
      out.write("		\n");
      out.write("		var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\n");
      out.write("		var imageSrc = 'https://ifh.cc/g/Gvw26t.png', // 마커이미지의 주소입니다\n");
      out.write("		//var imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png', // 마커이미지의 주소입니다    \n");
      out.write("	    imageSize = new kakao.maps.Size(30, 30), // 마커이미지의 크기입니다\n");
      out.write("	    //imageOption = {offset: new kakao.maps.Point(27, 69)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.\n");
      out.write("	    imageOption = {offset: new kakao.maps.Point(10, 10)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.\n");
      out.write("	      \n");
      out.write("		\n");
      out.write("		// 일반 지도와 스카이뷰로 지도 타입을 전환할 수 있는 지도타입 컨트롤을 생성합니다\n");
      out.write("		var mapTypeControl = new kakao.maps.MapTypeControl();\n");
      out.write("\n");
      out.write("		// 지도에 컨트롤을 추가해야 지도위에 표시됩니다\n");
      out.write("		// kakao.maps.ControlPosition은 컨트롤이 표시될 위치를 정의하는데 TOPRIGHT는 오른쪽 위를 의미합니다\n");
      out.write("		map.addControl(mapTypeControl, kakao.maps.ControlPosition.TOPRIGHT);\n");
      out.write("\n");
      out.write("		// 지도 확대 축소를 제어할 수 있는  줌 컨트롤을 생성합니다\n");
      out.write("		var zoomControl = new kakao.maps.ZoomControl();\n");
      out.write("		map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);\n");
      out.write("		\n");
      out.write("		// 마커가 표시될 위치입니다 \n");
      out.write("		var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption);\n");
      out.write("		var markerPosition  = new kakao.maps.LatLng(36.349268551597966 , 127.37767658950676); \n");
      out.write("		\n");
      out.write("		// 마커를 생성합니다\n");
      out.write("		var marker = new kakao.maps.Marker({\n");
      out.write("		    position: markerPosition,\n");
      out.write("		    image: markerImage\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		// 마커가 지도 위에 표시되도록 설정합니다\n");
      out.write("		marker.setMap(map);\n");
      out.write("		var iwContent = \n");
      out.write("			'<p style=\"width:200px\"><b>Seven Factory</b><br>대전광역시 대덕대로</p>';\n");
      out.write("			iwPosition = \n");
      out.write("			new daum.maps.LatLng(36.349268551597966 , 127.37767658950676);\n");
      out.write("\n");
      out.write("			var infowindow = new daum.maps.InfoWindow({\n");
      out.write("				position: iwPosition,\n");
      out.write("				content: iwContent,\n");
      out.write("				removable: true\n");
      out.write("				});\n");
      out.write("\n");
      out.write("			daum.maps.event.addListener(marker, 'click', function() {\n");
      out.write("				infowindow.open(map, marker);\n");
      out.write("				});\n");
      out.write("\n");
      out.write("		// 아래 코드는 지도 위의 마커를 제거하는 코드입니다\n");
      out.write("		// marker.setMap(null);    \n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("	<tr>\n");
      out.write("		<th colspan=\"2\">Location of Us</th>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>ADDRESS</td>\n");
      out.write("		<td>대전광역시 서구 대덕대로 182 오라클빌딩 10층</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>BY SUBWAY</td>\n");
      out.write("		<td>정부청사역 2번출구</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>BY BUS</td>\n");
      out.write("		<td>\n");
      out.write("		B:203, 211, 216, 301, 315, 316, 318, 604, 605, 617, 703, 706, 116, 3 /\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 정적인 페이지 포함 -->\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".fa-2x {\n");
      out.write("	font-size: 13px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wkmpm92bc1&submodules=geocoder\">\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("<div>\n");
      out.write("	<div class=\"footer\">\n");
      out.write("		<ul class=\"footer_menu\">\n");
      out.write("			<li>이용약관</li>\n");
      out.write("			<li>개인정보보호정책</li>\n");
      out.write("			<li>이메일 무단 수집 금지</li>\n");
      out.write("			<li>영상정보처리기기 설치 및 운영방침</li>\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		</ul>\n");
      out.write("		<ul class=\"company_info\">\n");
      out.write("			<li>우편번호 : 24901</li>\n");
      out.write("			<li>주소 : 대전광역시 서구 대덕대로 182 오라클빌딩 10층</li>\n");
      out.write("			<li>전화번호 : 02-313-7300</li>\n");
      out.write("			<li>팩스번호 : 02-313-0516</li>\n");
      out.write("			<li>이메일 : admin@sevenfactory.com</li>\n");
      out.write("		</ul>\n");
      out.write("		<ul class=\"company_info\">\n");
      out.write("			<li>사업체명 : sevenfactory</li>\n");
      out.write("			<li>대표자 : 강현 김승현 송인재 송지섭</li>\n");
      out.write("			<li>사업자등록번호 : 325-88-00678</li>\n");
      out.write("			<li>통신판매신고번호 : 2022-대전둔산-03148호</li>\n");
      out.write("		</ul>\n");
      out.write("		<p>Copyright © 2022 OsjMesiJJe inc. All rights reserved.</p>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/template/footer.jsp(22,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<a id=\"loginout\" href=\"sellerLoginform\"><i\n");
          out.write("					class=\"fas fa-sign-in-alt fa-2x\">사업자LOGIN</i></a>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
