/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-07 09:00:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sellerLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("   box-sizing: border-box;\r\n");
      out.write("   font-family: \"Inconsolata\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginout {\r\n");
      out.write("   margin-top: 40px;\r\n");
      out.write("   margin-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginout:hover {\r\n");
      out.write("   color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".test_1 {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   display: none;\r\n");
      out.write("   z-index: 200;\r\n");
      out.write("   position: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".test_1.open {\r\n");
      out.write("   display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".test_1.open:before {\r\n");
      out.write("   content: '';\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   z-index: 25;\r\n");
      out.write("   position: fixed;\r\n");
      out.write("   background: black;\r\n");
      out.write("   opacity: 0.4;\r\n");
      out.write("   top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".test_1 .test_2 {\r\n");
      out.write("   position: fixed;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   top: 50%;\r\n");
      out.write("   z-index: 30;\r\n");
      out.write("   background: white;\r\n");
      out.write("   left: 50%;\r\n");
      out.write("   width: 450px;\r\n");
      out.write("   padding: 20px 45px 50px;\r\n");
      out.write("   height: 630px;\r\n");
      out.write("   margin-top: -268px;\r\n");
      out.write("   margin-left: -255px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box h1 {\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-text {\r\n");
      out.write("   width: 360px;\r\n");
      out.write("   height: 47px;\r\n");
      out.write("   padding-left: 20px;\r\n");
      out.write("   border: 1px solid #d9d9d9;\r\n");
      out.write("   margin: 0 0 10px;\r\n");
      out.write("   font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find {\r\n");
      out.write("   float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginButton {\r\n");
      out.write("   border: none;\r\n");
      out.write("   width: 360px;\r\n");
      out.write("   padding: 10px 0;\r\n");
      out.write("   background: black;\r\n");
      out.write("   color: white;\r\n");
      out.write("   margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginButton:hover {\r\n");
      out.write("   outline: none;\r\n");
      out.write("   background: #5A5A5A;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#registerButton {\r\n");
      out.write("   border: none;\r\n");
      out.write("   width: 360px;\r\n");
      out.write("   padding: 10px 0;\r\n");
      out.write("   background: #E3EAF3;\r\n");
      out.write("   margin: 0 0 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#registerButton:hover {\r\n");
      out.write("   outline: none;\r\n");
      out.write("   background: #A4CAED;\r\n");
      out.write("}\r\n");
      out.write("/*    a {text-decoration: none; font-size: 0.9em; color: black;} */\r\n");
      out.write(".pop-up-close {\r\n");
      out.write("   border: none;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: -20.5px;\r\n");
      out.write("   right: -20px;\r\n");
      out.write("   width: 40px;\r\n");
      out.write("   height: 41px;\r\n");
      out.write("   text-indent: -9999px;\r\n");
      out.write("   background-color: transparent;\r\n");
      out.write("   background-image: url(resources/x-button.png);\r\n");
      out.write("   background-repeat: no-repeat;\r\n");
      out.write("   background-size: 100%;\r\n");
      out.write("   background-position: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wkmpm92bc1&submodules=geocoder\">\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   var filename;\r\n");
      out.write("\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("      //$('.test_1').css(\"display\",\"block\");\r\n");
      out.write("      $('.test_1').addClass('open');\r\n");
      out.write("\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : 'getImage',\r\n");
      out.write("         type : 'POST',\r\n");
      out.write("         dataType : 'JSON',\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            filename = data.filename;\r\n");
      out.write("            $('#getchaImg').attr(\"src\", \"resources/storage/\" + filename);\r\n");
      out.write("         },\r\n");
      out.write("         error : function() {\r\n");
      out.write("            alert('AJAX 통신이 실패했습니다1.');\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   function cc() {\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : 'getImage',\r\n");
      out.write("         type : 'POST',\r\n");
      out.write("         dataType : 'JSON',\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            filename = data.filename;\r\n");
      out.write("            $('#getchaImg').attr(\"src\", \"resources/storage/\" + filename);\r\n");
      out.write("         },\r\n");
      out.write("         error : function() {\r\n");
      out.write("            alert('AJAX 통신이 실패했습니다1.');\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("      $('#input_key').val('');\r\n");
      out.write("      $('#input_key').focus();\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function bbb() {\r\n");
      out.write("      location.href = 'main';\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      \r\n");
      out.write("      // 아이디 기억하기\r\n");
      out.write("      var savedID = getCookie(\"savedID\");\r\n");
      out.write("      $('#login_sId').val(savedID);\r\n");
      out.write("\r\n");
      out.write("      // savedID 가 있으면, 체크박스를 체크 상태로 유지\r\n");
      out.write("      if ($('#login_sId').val() != '') {\r\n");
      out.write("         $('#saveIDCheck').attr('checked', true);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // 체크박스의 상태가 변하면,\r\n");
      out.write("      $('#saveIDCheck').change(function() {\r\n");
      out.write("         // 체크되어 있다\r\n");
      out.write("         if ($('#saveIDCheck').is(':checked')) {\r\n");
      out.write("            setCookie(\"savedID\", $('#login_sId').val(), 7); // 7일간 쿠키에 보관\r\n");
      out.write("         }\r\n");
      out.write("         // 체크해제되어 있다.\r\n");
      out.write("         else {\r\n");
      out.write("            deleteCookie(\"savedID\");\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // 아이디를 입력할 때\r\n");
      out.write("      $('#login_sId').keyup(function() {\r\n");
      out.write("         // 체크되어 있다\r\n");
      out.write("         if ($('#saveIDCheck').is(':checked')) {\r\n");
      out.write("            setCookie(\"savedID\", $('#login_sId').val(), 7); // 7일간 쿠키에 보관\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   function fn_logout() {\r\n");
      out.write("      location.href = 'sellerlogout';\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function fn_login(f) {\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url : 'loginCheck',\r\n");
      out.write("         type : 'POST',\r\n");
      out.write("         dataType : 'JSON',\r\n");
      out.write("         data : 'input_key=' + $('#input_key').val(),\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            if (data.result == true) {\r\n");
      out.write("               $.ajax({\r\n");
      out.write("                  url : 'sellerlogin',\r\n");
      out.write("                  type : 'POST',\r\n");
      out.write("                  dataType : 'JSON',\r\n");
      out.write("                  data : 'sId=' + $('#login_sId').val() + '&sPw='\r\n");
      out.write("                        + $('#login_sPw').val(),\r\n");
      out.write("                  success : function(data) {\r\n");
      out.write("                     if (data.result != 'YES') {\r\n");
      out.write("                        alert('로그인 실패 아이디와 비밀번호를 확인하세요.');\r\n");
      out.write("                        $('#login_sPw').val('');\r\n");
      out.write("                        $('#input_key').val('');\r\n");
      out.write("                        $('#login_sPw').focus();\r\n");
      out.write("                        cc();\r\n");
      out.write("                     } else {\r\n");
      out.write("                        var url = 'sellerMain?sId='+$('#login_sId').val();\r\n");
      out.write("                        location.href = url;\r\n");
      out.write("                        /* location.reload(); */}\r\n");
      out.write("                  },\r\n");
      out.write("                  error : function() {\r\n");
      out.write("                     alert('AJAX 통신이 실패했습니다.2');\r\n");
      out.write("                  }\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("               alert('그림의 인증번호와 입력하신 인증번호가 다릅니다.');\r\n");
      out.write("               $('#input_key').val('');\r\n");
      out.write("               $('#input_key').focus();\r\n");
      out.write("               cc();\r\n");
      out.write("            }\r\n");
      out.write("         },\r\n");
      out.write("         error : function() {\r\n");
      out.write("            alert('AJAX 통신이 실패했습니다.2');\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   // 1. 쿠키 만들기\r\n");
      out.write("   function setCookie(cookieName, value, exdays) {\r\n");
      out.write("      var exdate = new Date();\r\n");
      out.write("      exdate.setDate(exdate.getDate() + exdays);\r\n");
      out.write("      var cookieValue = escape(value)\r\n");
      out.write("            + ((exdays == null) ? \"\" : \"; expires=\" + exdate.toGMTString());\r\n");
      out.write("      document.cookie = cookieName + \"=\" + cookieValue;\r\n");
      out.write("   }\r\n");
      out.write("   // 2. 쿠키 삭제\r\n");
      out.write("   function deleteCookie(cookieName) {\r\n");
      out.write("      var expireDate = new Date();\r\n");
      out.write("      expireDate.setDate(expireDate.getDate() - 1);\r\n");
      out.write("      document.cookie = cookieName + \"= \" + \"; expires=\"\r\n");
      out.write("            + expireDate.toGMTString();\r\n");
      out.write("   }\r\n");
      out.write("   // 3. 쿠키 가져오기\r\n");
      out.write("   function getCookie(cookieName) {\r\n");
      out.write("      cookieName = cookieName + \"=\";\r\n");
      out.write("      var cookieData = document.cookie;\r\n");
      out.write("      var start = cookieData.indexOf(cookieName);\r\n");
      out.write("      var cookieValue = \"\";\r\n");
      out.write("      if (start != -1) {\r\n");
      out.write("         start += cookieName.length;\r\n");
      out.write("         var end = cookieData.indexOf(\";\", start);\r\n");
      out.write("         if (end == -1) {\r\n");
      out.write("            end = cookieData.length;\r\n");
      out.write("         }\r\n");
      out.write("         cookieValue = cookieData.substring(start, end);\r\n");
      out.write("      }\r\n");
      out.write("      return unescape(cookieValue);\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"test_1\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"test_2\">\r\n");
      out.write("               <div id=\"login\" class=\"login-box\">\r\n");
      out.write("                  <form method=\"POST\">\r\n");
      out.write("                     <h1>LOGIN</h1>\r\n");
      out.write("                     <br /> \r\n");
      out.write("                     <input class=\"login-text\" id=\"login_sId\" type=\"text\" name=\"login_sId\" placeholder=\"사업자번호\" autofocus /><br /> \r\n");
      out.write("                     <input class=\"login-text\" id=\"login_sPw\" type=\"password\" name=\"login_sPw\" placeholder=\"사업자 비밀번호\" /><br /> \r\n");
      out.write("                     <input id=\"saveIDCheck\" type=\"checkbox\" name=\"saveIDCheck\" value=\"true\" checked />아이디 기억하기 \r\n");
      out.write("                     <img id=\"getchaImg\" src=\"\" style=\"width: 360px; height: 120px;\" /> \r\n");
      out.write("                     <input id=\"input_key\" type=\"text\" name=\"input_key\" style=\"margin-top: 5px;\" /> \r\n");
      out.write("                     <a href=\"javascript:void(0);\" onclick=\"cc()\">\r\n");
      out.write("                     <i class=\"fas fa-redo-alt\"></i>새로고침</a><br /> \r\n");
      out.write("                     <input id=\"loginButton\" type=\"button\" value=\"로그인\" onclick=\"fn_login(this.form)\" /> \r\n");
      out.write("                     <input id=\"registerButton\" type=\"button\" value=\"회원가입\" onclick=\"location.href='sellerRegisterPage'\" />\r\n");
      out.write("                     <div class=\"find\">\r\n");
      out.write("                        &nbsp;|&nbsp; <a href=\"findSellerPwPage\">비밀번호 찾기</a><br/>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div>\r\n");
      out.write("               <button class=\"pop-up-close\" onclick=\"bbb()\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
