/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-07 08:12:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qnaBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaBoardViewPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/template/footer.jsp", Long.valueOf(1667795532121L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654647991285L));
    _jspx_dependants.put("jar:file:/C:/sevenfactory/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/sevenfactory_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 동적인 페이지 포함 -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/template/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("QNA게시판", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("   var qPw = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qPw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   function fn_update(f){\n");
      out.write("      f.action = 'qnaBoardUpdatePage';\n");
      out.write("      f.submit();\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_delete(f){\n");
      out.write("      var qPwCheck = prompt('비밀번호를 입력해주세요');\n");
      out.write("      if(qPwCheck == qPw){\n");
      out.write("         if(confirm('삭제하시겠습니까?')){\n");
      out.write("            f.action = 'qnaBoardDelete';\n");
      out.write("            f.submit();\n");
      out.write("         }\n");
      out.write("      }else{\n");
      out.write("         alert('비밀번호가 틀렸습니다.');\n");
      out.write("      }\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_replyInsert(f){\n");
      out.write("      if(f.reContent.value == ''){\n");
      out.write("         alert('답변을 입력해주세요');\n");
      out.write("      }else{\n");
      out.write("         f.action = 'qnaBoardReplyInsert';\n");
      out.write("         f.submit();\n");
      out.write("      }\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_replyDelete(f){\n");
      out.write("      if(confirm('답변을 삭제하시겠습니까?')){\n");
      out.write("         f.action = 'qnaBoardReplyDelete';\n");
      out.write("         f.submit();\n");
      out.write("      }\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_replyUpdate(f){\n");
      out.write("      \n");
      out.write("      var reNo = f.reNo.value;\n");
      out.write("      var reContent = document.querySelector('#reContent'+reNo);\n");
      out.write("      var reContentUpdateBox = document.querySelector('#reContentUpdateBox'+reNo);\n");
      out.write("      var updateBtn = document.querySelector('#updateBtn'+reNo);\n");
      out.write("      var deleteBtn = document.querySelector('#deleteBtn'+reNo);\n");
      out.write("      var saveBtn = document.querySelector('#saveBtn'+reNo);\n");
      out.write("      var cancelBtn = document.querySelector('#cancelBtn'+reNo);\n");
      out.write("      \n");
      out.write("      if(updateBtn.value == '수정'){\n");
      out.write("         update();\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      function update(){\n");
      out.write("         reContent.style.display = 'none';\n");
      out.write("         reContentUpdateBox.style.display = 'inline';\n");
      out.write("         reContentUpdateBox.style.width = '100%';\n");
      out.write("         reContentUpdateBox.style.height = '100%';\n");
      out.write("         updateBtn.style.display = 'none';\n");
      out.write("         deleteBtn.style.display = 'none';\n");
      out.write("         saveBtn.style.display = 'inline';\n");
      out.write("         cancelBtn.style.display = 'inline';\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_replyCancel(f){\n");
      out.write("      \n");
      out.write("      var reNo = f.reNo.value;\n");
      out.write("      var reContent = document.querySelector('#reContent'+reNo);\n");
      out.write("      var reContentUpdateBox = document.querySelector('#reContentUpdateBox'+reNo);\n");
      out.write("      var updateBtn = document.querySelector('#updateBtn'+reNo);\n");
      out.write("      var deleteBtn = document.querySelector('#deleteBtn'+reNo);\n");
      out.write("      var saveBtn = document.querySelector('#saveBtn'+reNo);\n");
      out.write("      var cancelBtn = document.querySelector('#cancelBtn'+reNo);\n");
      out.write("      \n");
      out.write("      if(cancelBtn.value == '취소'){\n");
      out.write("         cancel();\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      function cancel(){\n");
      out.write("         reContent.style.display = 'inline';\n");
      out.write("         reContentUpdateBox.style.display = 'none';\n");
      out.write("         updateBtn.style.display = 'inline';\n");
      out.write("         deleteBtn.style.display = 'inline';\n");
      out.write("         saveBtn.style.display = 'none';\n");
      out.write("         cancelBtn.style.display = 'none';\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_replySave(f){\n");
      out.write("      var updateReContent = f.updateReContent.value;\n");
      out.write("      if(updateReContent == ''){\n");
      out.write("         alert('내용을 입력해주세요');\n");
      out.write("      }else{\n");
      out.write("         f.action = 'qnaBoardReplyUpdate';\n");
      out.write("         f.submit();\n");
      out.write("      }\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   $(function() {\n");
      out.write("         $('#reContentInsertBox').keyup(function (e){\n");
      out.write("             var content = $(this).val();\n");
      out.write("             $(this).height(((content.split('\\n').length + 1) * 1.5) + 'em');\n");
      out.write("             $('#counter1').html(content.length + '/100');\n");
      out.write("         });\n");
      out.write("         $('#reContentInsertBox').keyup();\n");
      out.write("         \n");
      out.write("         $('#reContentInsertBox').on('keyup', function(){\n");
      out.write("           if($(this).val().length > 100){\n");
      out.write("              $(this).val($(this).val().substring(0, 100));\n");
      out.write("           }\n");
      out.write("        });\n");
      out.write("   });\n");
      out.write("   \n");
      out.write("   \n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("   .qnaBoard-viewBox{\n");
      out.write("      width: 1100px; \n");
      out.write("      margin-bottom: 20px;  \n");
      out.write("      margin: 50px auto;\n");
      out.write("      text-align: center;\n");
      out.write("   }\n");
      out.write("   .qnaBoard-viewBox table{\n");
      out.write("      width: 1100px;\n");
      out.write("      margin: 20px auto;\n");
      out.write("      border-collapse: collapse;\n");
      out.write("   }\n");
      out.write("   .qnaBoard-viewBox th, td{\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("   }\n");
      out.write("   .qnaBoard-viewBox th{\n");
      out.write("      background: #EAF2FF;\n");
      out.write("      width: 110px;\n");
      out.write("   }\n");
      out.write("   .title-table th, td{\n");
      out.write("      padding: 5px;\n");
      out.write("   }\n");
      out.write("   .title-table td{\n");
      out.write("      text-align: left;\n");
      out.write("   }\n");
      out.write("   .title-table tbody tr:nth-of-type(1) input{\n");
      out.write("      float: left;\n");
      out.write("      padding: 3px;\n");
      out.write("      width: 300px;\n");
      out.write("   }\n");
      out.write("   .title-table tbody tr:nth-of-type(2) input{\n");
      out.write("      float: left;\n");
      out.write("      padding: 3px;\n");
      out.write("      width: 795px;\n");
      out.write("   }\n");
      out.write("   .content-table{\n");
      out.write("      height: 500px;\n");
      out.write("   }\n");
      out.write("   .content-table tbody tr td{\n");
      out.write("      text-align: left;\n");
      out.write("      white-space: pre-line;\n");
      out.write("   }\n");
      out.write("   .content-table tfoot tr td{\n");
      out.write("      border: none;\n");
      out.write("   }\n");
      out.write("    .content-table .qnaBtn {\n");
      out.write("      float: right;\n");
      out.write("      background: white;\n");
      out.write("      cursor: pointer;\n");
      out.write("      padding: 10px;\n");
      out.write("      width : 67px;\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("    }\n");
      out.write("   .qnaBoardReply-insertBox{\n");
      out.write("      margin: 0 auto;\n");
      out.write("      width: 1100px;\n");
      out.write("      text-align: center;\n");
      out.write("   }\n");
      out.write("   .reply-insertBox{\n");
      out.write("      width: 1100px;\n");
      out.write("   }\n");
      out.write("   .reply-insertBox th{\n");
      out.write("      width: 110px;\n");
      out.write("      background: #EAF2FF;\n");
      out.write("   }\n");
      out.write("   .reply-insertTable{\n");
      out.write("      margin: 0 auto;\n");
      out.write("      width: 1100px;\n");
      out.write("   }\n");
      out.write("   .reply-insertTable th, td{\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("   }\n");
      out.write("   .reply-insertTable td:nth-of-type(2){\n");
      out.write("      border: none;\n");
      out.write("   }\n");
      out.write("   .reply-insertTable input {\n");
      out.write("   	  width: 80px;   \n");
      out.write("      padding: 5px;\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("      background: white;\n");
      out.write("      cursor: pointer;\n");
      out.write("   }\n");
      out.write("   .reply-insertTable tr:nth-of-type(2) td{\n");
      out.write("      height: 10px;\n");
      out.write("      border: none;\n");
      out.write("   }\n");
      out.write("   .reply-insertTable tr:nth-of-type(2) td input{\n");
      out.write("      height: 100%;\n");
      out.write("   }\n");
      out.write("   .limited_text_wrap1{\n");
      out.write("      width: 990px;\n");
      out.write("      height: auto;\n");
      out.write("      position: relative;\n");
      out.write("      display: inline-block;\n");
      out.write("   }\n");
      out.write("   .limited_text_wrap1 textarea{\n");
      out.write("      width: 100%;\n");
      out.write("      resize: none;\n");
      out.write("      min-height: 9.5em;\n");
      out.write("      line-height: 1.6em;\n");
      out.write("      max-height: 9em;\n");
      out.write("   }\n");
      out.write("   .limited_text_wrap1 span{\n");
      out.write("      position: absolute;\n");
      out.write("      bottom: 10px;\n");
      out.write("      right: 10px;\n");
      out.write("   }\n");
      out.write("   #counter1{\n");
      out.write("      border-radius: 5px;\n");
      out.write("      padding: 0 5px 0 5px;\n");
      out.write("      font-size: 1.35em;\n");
      out.write("   }\n");
      out.write("   .qnaBoardReply-viewBox{\n");
      out.write("      margin: 0 auto;\n");
      out.write("      width: 1100px;\n");
      out.write("      margin-bottom: 50px;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable{\n");
      out.write("      margin: 0 auto;\n");
      out.write("      width: 1100px;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable th, td{\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable input:nth-of-type(1){\n");
      out.write("      padding: 10px;\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("      background: white;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable input:nth-of-type(2){\n");
      out.write("      padding: 10px;\n");
      out.write("      border: 1px solid lightgray;\n");
      out.write("      background: white;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable tr td:nth-of-type(1){\n");
      out.write("      width: 100px;\n");
      out.write("      text-align: center;\n");
      out.write("      font-weight: bold;\n");
      out.write("      background: #EAF2FF;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable tr td:nth-of-type(2){\n");
      out.write("      width: 860px;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable tr td:nth-of-type(3){\n");
      out.write("      width: 70px;\n");
      out.write("   }\n");
      out.write("   .reply-viewTable tr td:nth-of-type(4){\n");
      out.write("      background: aqua;\n");
      out.write("      width: 70px;\n");
      out.write("      white-space: pre-line;\n");
      out.write("   }\n");
      out.write("   .hidden-row{\n");
      out.write("      border: none;\n");
      out.write("      background: white;\n");
      out.write("   }\n");
      out.write("   .qna_backimg {\n");
      out.write("      width: 100%; \n");
      out.write("      height: 750px; \n");
      out.write("      background-size: cover;\n");
      out.write("      background-image: url(\"resources/assets/background_img/backimg.jpg\"); \n");
      out.write("      text-align: center; \n");
      out.write("      color: white; \n");
      out.write("      padding-top: 300px;   \n");
      out.write("   }\n");
      out.write("   #pagetitle {font-size: 85px;}\n");
      out.write("   #sevenfactory, #explain {font-weight: bold;}\n");
      out.write("   #explain {font-size: 15px;}\n");
      out.write("   #qna_name {width: 200px;}\n");
      out.write("</style>\n");
      out.write("<div class=\"qna_backimg\">\n");
      out.write("   <h3 id=\"sevenfactory\">Together</h3>\n");
      out.write("   <h1 id=\"pagetitle\">Community</h1>\n");
      out.write("   <p id=\"explain\">투개더에 대한 관련 질문</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"qnaBoard-viewBox\">\n");
      out.write("	<img id=\"qna_name\" alt=\"qna_name\" src=\"resources/assets/name_img/qna_name.png\"/><br/> \n");
      out.write("   <form method=\"POST\">\n");
      out.write("      <div class=\"viewBox\">\n");
      out.write("         <table class=\"title-table\">\n");
      out.write("            <tbody>\n");
      out.write("               <tr>\n");
      out.write("                  <th>NAME</th>\n");
      out.write("                  <td>\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                  </td>\n");
      out.write("                  <th>NOTICEDATE</th>\n");
      out.write("                  <td>\n");
      out.write("                     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qNoticedate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                  </td>\n");
      out.write("               </tr>\n");
      out.write("               <tr>\n");
      out.write("                  <th>TITLE</th>\n");
      out.write("                  <td colspan=\"3\">\n");
      out.write("                     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                  </td>\n");
      out.write("               </tr>\n");
      out.write("            </tbody>\n");
      out.write("         </table>\n");
      out.write("         <br/>\n");
      out.write("         <table class=\"content-table\">\n");
      out.write("            <tbody>\n");
      out.write("               <tr>\n");
      out.write("                  <th>CONTENT</th>\n");
      out.write("                  <td>\n");
      out.write("                     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                  </td>\n");
      out.write("               </tr>\n");
      out.write("            </tbody>\n");
      out.write("            <tfoot>\n");
      out.write("               <tr>\n");
      out.write("                  <td colspan=\"2\">\n");
      out.write("                     <input class=\"qnaBtn\" type=\"button\" value=\"LIST\" style=\"display: inline-block;\" onclick=\"location.href='qnaBoardList'\"/>\n");
      out.write("                     <input class=\"qnaBtn\" type=\"button\" value=\"DELETE\" style=\"display: inline-block;\" onclick=\"fn_delete(this.form)\"/>\n");
      out.write("                     <input class=\"qnaBtn\" type=\"button\" value=\"UPDATE\" style=\"display: inline-block;\" onclick=\"fn_update(this.form)\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"qNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"qPw\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qPw }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"mId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.mId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"qTitle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"qContent\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"page\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                  </td>\n");
      out.write("               </tr>\n");
      out.write("            </tfoot>\n");
      out.write("         </table>\n");
      out.write("      </div>\n");
      out.write("   </form>\n");
      out.write("</div>\n");
      out.write("<br/>\n");
      out.write("<div class=\"qnaBoardReply-insertBox\">\n");
      out.write("<img id=\"qna_name\" alt=\"qna_name\" src=\"resources/assets/name_img/answer_name.png\"/><br/> \n");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</div> \n");
      out.write("<div class=\"qnaBoardReply-viewBox\">\n");
      out.write("   <table class=\"reply-viewTable\">\n");
      out.write("      <tbody>\n");
      out.write("         ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("         ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("   </table>\n");
      out.write("</div>\n");
      out.write("<!-- 정적인 페이지 포함 -->\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".fa-2x {\n");
      out.write("	font-size: 13px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wkmpm92bc1&submodules=geocoder\">\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("<div>\n");
      out.write("	<div class=\"footer\">\n");
      out.write("		<ul class=\"footer_menu\">\n");
      out.write("			<li>이용약관</li>\n");
      out.write("			<li>개인정보보호정책</li>\n");
      out.write("			<li>이메일 무단 수집 금지</li>\n");
      out.write("			<li>영상정보처리기기 설치 및 운영방침</li>\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		</ul>\n");
      out.write("		<ul class=\"company_info\">\n");
      out.write("			<li>우편번호 : 24901</li>\n");
      out.write("			<li>주소 : 대전광역시 서구 대덕대로 182 오라클빌딩 10층</li>\n");
      out.write("			<li>전화번호 : 02-313-7300</li>\n");
      out.write("			<li>팩스번호 : 02-313-0516</li>\n");
      out.write("			<li>이메일 : admin@sevenfactory.com</li>\n");
      out.write("		</ul>\n");
      out.write("		<ul class=\"company_info\">\n");
      out.write("			<li>사업체명 : sevenfactory</li>\n");
      out.write("			<li>대표자 : 강현 김승현 송인재 송지섭</li>\n");
      out.write("			<li>사업자등록번호 : 325-88-00678</li>\n");
      out.write("			<li>통신판매신고번호 : 2022-대전둔산-03148호</li>\n");
      out.write("		</ul>\n");
      out.write("		<p>Copyright © 2022 OsjMesiJJe inc. All rights reserved.</p>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(309,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.nmName ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.nmName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(312,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.nmName eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.mId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(361,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("   ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(362,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mId eq 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("      <div class=\"reply-insertBox\">\n");
          out.write("         <form method=\"POST\">\n");
          out.write("            <table class=\"reply-insertTable\">\n");
          out.write("               <tr>\n");
          out.write("                  <th>admin</th>\n");
          out.write("                  <td>\n");
          out.write("                     <div class=\"limited_text_wrap1\">\n");
          out.write("                        <textarea id=\"reContentInsertBox\" name=\"reContent\" placeholder=\"답변을 100자 이내로 기재해 주세요.\"></textarea>\n");
          out.write("                        <span id=\"counter1\">###</span>\n");
          out.write("                     </div>\n");
          out.write("                  </td>\n");
          out.write("               </tr>\n");
          out.write("               <tr>\n");
          out.write("                  <td colspan=\"2\">\n");
          out.write("                     <input type=\"button\" value=\"등록\" onclick=\"fn_replyInsert(this.form)\"/>\n");
          out.write("                     <input type=\"hidden\" name=\"mId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                     <input type=\"hidden\" name=\"qNo\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                     <input type=\"hidden\" name=\"page\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                  </td>\n");
          out.write("               </tr>\n");
          out.write("            </table>\n");
          out.write("         </form>\n");
          out.write("      </div>\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(392,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty reList }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <tr>\n");
          out.write("               <th colspan=\"4\">아직 답변이 등록되지 않았습니다</th>\n");
          out.write("            </tr>\n");
          out.write("         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(397,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty reList }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f5, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(398,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("reDTO");
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(398,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(398,12) '${reList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("               <form method=\"POST\">\n");
            out.write("                  <tr>\n");
            out.write("                     <td><span id=\"mId\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.mId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("                     <td>\n");
            out.write("                        <span id=\"reContent");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                        <textarea id=\"reContentUpdateBox");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" name=\"updateReContent\" style=\"display: none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</textarea>\n");
            out.write("                     </td>\n");
            out.write("                     ");
            if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                  </tr>\n");
            out.write("               </form>\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(406,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        ");
          if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fif_005f6, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f6);
      // /WEB-INF/views/qnaBoard/qnaBoardViewPage.jsp(407,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mId eq 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                           <th>\n");
          out.write("                              <input id=\"updateBtn");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"button\" value=\"수정\" onclick=\"fn_replyUpdate(this.form)\"/>\n");
          out.write("                              <input id=\"saveBtn");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"display:none\" type=\"button\" value=\"저장\" onclick=\"fn_replySave(this.form)\"/>\n");
          out.write("                                <input type=\"hidden\" name=\"reNo\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("		                        <input type=\"hidden\" name=\"qNo\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qDTO.qNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("		                        <input type=\"hidden\" name=\"page\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                           </th>\n");
          out.write("                           <th>\n");
          out.write("                              <input id=\"deleteBtn");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"button\" value=\"삭제\" onclick=\"fn_replyDelete(this.form)\"/>\n");
          out.write("                              <input id=\"cancelBtn");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reDTO.reNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"display:none\" type=\"button\" value=\"취소\" onclick=\"fn_replyCancel(this.form)\"/>\n");
          out.write("                           </th>\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /WEB-INF/views/template/footer.jsp(22,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<a id=\"loginout\" href=\"sellerLoginform\"><i\n");
          out.write("					class=\"fas fa-sign-in-alt fa-2x\">사업자LOGIN</i></a>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
