/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-09 07:37:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Date;

public final class reservationPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/template/footer.jsp", Long.valueOf(1667795532121L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654647991285L));
    _jspx_dependants.put("jar:file:/C:/sevenfactory/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/sevenfactory_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Date");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 동적인 페이지 포함 -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/template/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("객실예약", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("history.replaceState({}, null, location.pathname);\n");
      out.write("</script>  \n");
      out.write("<style type=\"text/css\">\n");
      out.write("   #selectedRoomContainer h3 {\n");
      out.write("      border-bottom: 2px solid #e9e9e9;\n");
      out.write("   }\n");
      out.write("   #selectedRoomContainer table{\n");
      out.write("      margin: auto;\n");
      out.write("      border-collapse: collapse;\n");
      out.write("      text-align: center;\n");
      out.write("   }\n");
      out.write("   #selectedRoomContainer{\n");
      out.write("      width: 1200px;\n");
      out.write("      margin: auto;\n");
      out.write("      margin-bottom: 50px;\n");
      out.write("   }\n");
      out.write("   #step1{\n");
      out.write("      display:flex;\n");
      out.write("   }\n");
      out.write("   #step2{\n");
      out.write("      display:none;\n");
      out.write("   }\n");
      out.write("   #step_img{\n");
      out.write("      width:1208px;height: 70px;margin-bottom: 20px;\n");
      out.write("   }\n");
      out.write("   .step1_left {\n");
      out.write("      width : 600px;\n");
      out.write("   }\n");
      out.write("   .step1_right {\n");
      out.write("      width : 600px;\n");
      out.write("      margin-left: 8px;\n");
      out.write("   }\n");
      out.write("   .con_tit {\n");
      out.write("       position: relative;\n");
      out.write("          padding: 20px 20px;\n");
      out.write("       background: #e9e9e9;\n");
      out.write("   }\n");
      out.write("   .con_desc {\n");
      out.write("       padding: 15px 20px 30px;\n");
      out.write("       border : 1px solid #e9e9e9;\n");
      out.write("   }\n");
      out.write("   .step1_user_info {\n");
      out.write("    border: 1px solid #e9e9e9;\n");
      out.write("    width: 100%;\n");
      out.write("    padding: 20px 0;\n");
      out.write("      }\n");
      out.write("   #stepUpBtn {\n");
      out.write("      border: none;\n");
      out.write("       /* margin: auto; */\n");
      out.write("       /* text-align: center; */\n");
      out.write("       width: 50%;\n");
      out.write("       height: 50px;\n");
      out.write("       margin-top: 50px;\n");
      out.write("       margin-left: 150px;\n");
      out.write("       font-weight: bold;\n");
      out.write("   }\n");
      out.write("   .step1_user_info input[type=\"text\"]{\n");
      out.write("      border : none;\n");
      out.write("   }\n");
      out.write("   .step1_user_info td:nth-of-type(1) {\n");
      out.write("   width: 30%;\n");
      out.write("   height: 50px;\n");
      out.write("   font-weight: bold;\n");
      out.write("   margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("   .step1_user_info td:nth-of-type(2) {\n");
      out.write("   width: 245px;\n");
      out.write("   height: 50px;\n");
      out.write("   margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("   \n");
      out.write("   #selected_room{\n");
      out.write("      width:100%\n");
      out.write("   }\n");
      out.write("   #selected_room tr:nth-of-type(1) {\n");
      out.write("    border-bottom: 1px solid #e9e9e9;\n");
      out.write("}\n");
      out.write("   #selected_room tr:last-of-type {\n");
      out.write("    border-bottom: 1px solid #e9e9e9;\n");
      out.write("}\n");
      out.write("   #step2-bottom{\n");
      out.write("      display : flex;\n");
      out.write("      margin-top: 20px;\n");
      out.write("      margin-bottom: 50px;\n");
      out.write("      height: 300px;\n");
      out.write("   }\n");
      out.write("   #step2-bottom-left{\n");
      out.write("      width: 600px; \n");
      out.write("      margin-right: 8px;\n");
      out.write("      text-align: center;\n");
      out.write("   }\n");
      out.write("   #step2-bottom-right{\n");
      out.write("      width: 600px;\n");
      out.write("      text-align: center;\n");
      out.write("   }\n");
      out.write("   #bill-table{\n");
      out.write("      width: 100%;\n");
      out.write("      height : 100%;\n");
      out.write("      margin-top: 10px;\n");
      out.write("   }\n");
      out.write("   #bill-table th{\n");
      out.write("      width: 40%;\n");
      out.write("      height : 40px;\n");
      out.write("   }\n");
      out.write("   #bill-table td:nth-of-type(1) {\n");
      out.write("      width: 30%;\n");
      out.write("      height : 40px;\n");
      out.write("   }\n");
      out.write("   #bill-table td:nth-of-type(2) {\n");
      out.write("      width: 40%;\n");
      out.write("      height : 40px;\n");
      out.write("   }\n");
      out.write("   #payBtn{\n");
      out.write("   border: none;\n");
      out.write("    margin: auto;\n");
      out.write("    text-align: center;\n");
      out.write("    width: 50%;\n");
      out.write("    height: 50px;\n");
      out.write("    margin-top: 50px;\n");
      out.write("    font-weight: bold;\n");
      out.write("   }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.2.0.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("   var basicPrice = 0;\n");
      out.write("   var nights = 0;\n");
      out.write("   var addPrice = 0;\n");
      out.write("   var totalPrice = 0;\n");
      out.write("   var phoneFlag = false;\n");
      out.write("   var isLogin = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("   var firstPrice = 0;\n");
      out.write("   var secondPrice = 0;\n");
      out.write("   var gPrice = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("   var gName ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("   var mName = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("   var mPhone = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mPhone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("   var mEmail ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("   $(document).ready(function(){\n");
      out.write("      var regExpPHONE = /^01[0|1|6|9][0-9]{3,4}[0-9]{4}$/;\n");
      out.write("      //포인트 일단 0으로 넣기\n");
      out.write("      $('input[name=use_point]').attr('value',0);\n");
      out.write("      \n");
      out.write("      $('#nmPhone').keyup(function(){\n");
      out.write("         if ( regExpPHONE.test($('#nmPhone').val()) ) {\n");
      out.write("            $('#phoneCheckResult').text('사용 가능한 번호입니다.');\n");
      out.write("            $('#phoneCheckResult').css('color', 'blue').css('font-weight', 'bold');\n");
      out.write("            phoneFlag = true;\n");
      out.write("         } else {\n");
      out.write("            $('#phoneCheckResult').text('사용 불가능한 번호입니다.');\n");
      out.write("            $('#phoneCheckResult').css('color', 'red');\n");
      out.write("            phoneFlag = false;\n");
      out.write("         }\n");
      out.write("      });\n");
      out.write("   \n");
      out.write("      $('#stepUpBtn').click(function(){\n");
      out.write("         if (!($(\"#ag_use\").is(':checked'))) {\n");
      out.write("            alert('이용시 유의사항을 읽어보시고 동의하셔야 됩니다.');\n");
      out.write("            return;\n");
      out.write("         }\n");
      out.write("         if (!($(\"#ag_adult\").is(':checked'))) {\n");
      out.write("            alert('성인 확인에 동의하셔야 됩니다.');\n");
      out.write("            return;\n");
      out.write("         }else if ($(\"#nmName\").val() == ''){\n");
      out.write("            alert('성함을 입력해주세요.');\n");
      out.write("            $(\"#nmName\").focus();\n");
      out.write("            return;\n");
      out.write("         }else if($(\"#nmPhone\").val() == '') {\n");
      out.write("            alert('전화번호를 입력해주세요.');\n");
      out.write("            $(\"#nmPhone\").focus();\n");
      out.write("            return;\n");
      out.write("         }else if (!phoneFlag) {\n");
      out.write("            alert('전화번호를 확인해주세요.');\n");
      out.write("            $(\"#nmPhone\").focus();\n");
      out.write("            $(\"#nmPhone\").val('');\n");
      out.write("            return;\n");
      out.write("         }\n");
      out.write("         nmPhone = $(\"#nmPhone\").val();\n");
      out.write("         nmName =   $(\"#nmName\").val();\n");
      out.write("         fn_stepUp();\n");
      out.write("      \n");
      out.write("      });\n");
      out.write("      \n");
      out.write("      $('#all_agree').click(function () {\n");
      out.write("          \n");
      out.write("          var all_check_is = $(\"#all_agree\").is(':checked');\n");
      out.write("            \n");
      out.write("              if (all_check_is == true) {\n");
      out.write("                  $('#ag_use').attr(\"checked\", true);\n");
      out.write("                  $('#ag_adult').attr(\"checked\", true);\n");
      out.write("              } else if (all_check_is == false) {\n");
      out.write("                  $('#ag_use').attr(\"checked\", false);\n");
      out.write("                  $('#ag_adult').attr(\"checked\", false);\n");
      out.write("              }\n");
      out.write("         });\n");
      out.write("   });\n");
      out.write("    window.onload = function(){\n");
      out.write("         var rCheckIn = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("         var rCheckOut = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckOut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("         var arr1 = rCheckIn.split('-');\n");
      out.write("         var arr2 = rCheckOut.split('-');\n");
      out.write("         var dat1 = new Date(arr1[0], arr1[1], arr1[2]);\n");
      out.write("         var dat2 = new Date(arr2[0], arr2[1], arr2[2]);\n");
      out.write("         \n");
      out.write("         var diff = dat2 - dat1;\n");
      out.write("         var currDay = 24*60*60*1000;\n");
      out.write("         nights = parseInt(diff/currDay);\n");
      out.write("         basicPrice = gPrice * nights;\n");
      out.write("         $('#basicPrice').html(basicPrice);\n");
      out.write("         $('#nights').html(nights + \"박\");\n");
      out.write("         $('#firstPrice').html(gPrice);\n");
      out.write("  \n");
      out.write("         if (isLogin != ''){\n");
      out.write("           fn_stepUp();\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("\n");
      out.write("   function fn_change(){\n");
      out.write("         selectItem = $(\"#selectPeople\").val();\n");
      out.write("         //2+4\n");
      out.write("         //4\n");
      out.write("         var standardPeople = 2;\n");
      out.write("         var condition = selectItem - standardPeople;\n");
      out.write("          //4-2=2\n");
      out.write("         if(condition == 0){\n");
      out.write("            addPrice = 0;\n");
      out.write("         }else if(condition == 1){\n");
      out.write("            addPrice = 20000;\n");
      out.write("         }else if(condition ==2){\n");
      out.write("            addPrice =40000;\n");
      out.write("         }else{\n");
      out.write("            addPrice = 0;\n");
      out.write("         }\n");
      out.write("         totalPrice = basicPrice + addPrice;\n");
      out.write("         $('#addPrice').html(\"+\"+addPrice + \"원\");\n");
      out.write("         if(mName.equals(\"\")){\n");
      out.write("        	 $('#totalPrice').html(totalPrice + \"원\");\n");
      out.write("             $('#totalPrice').css('fontWeight','bold').css('color','red');\n");
      out.write("             document.getElementById('rPrice').value = totalPrice;\n");
      out.write("         }\n");
      out.write("         \n");
      out.write("      }\n");
      out.write("  \n");
      out.write("   	window.addEventListener('keyup', function(event) {\n");
      out.write("      var point = document.getElementById(\"use_point\").value;\n");
      out.write("      totalPrice = basicPrice + addPrice - point;\n");
      out.write("      $('#totalPrice').html(totalPrice + \"원\");\n");
      out.write("       $('#totalPrice').css('fontWeight','bold').css('color','red');\n");
      out.write("       document.getElementById('rPrice').value = totalPrice;\n");
      out.write("   });\n");
      out.write("   \n");
      out.write("   \n");
      out.write("//카카오페이\n");
      out.write("function fn_kakaopay1(f){\n");
      out.write("       var gNo ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       var mNo = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       var mEmail ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       var rCheckIn ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckIn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       var rCheckOut ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckOut }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       var hNo ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.hNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       var point ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("       \n");
      out.write("      if($(\"#selectPeople\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(").val() == ''){\n");
      out.write("            alert('인원을 선택해주세요.');\n");
      out.write("            return;\n");
      out.write("         }else if ($(\"#use_point\").val()>point){\n");
      out.write("            alert('사용가능한 포인트를 확인해주세요');\n");
      out.write("            document.getElementById(\"use_point\").focus();\n");
      out.write("         }else{\n");
      out.write("            IMP.init('imp81561510');\n");
      out.write("             IMP.request_pay({\n");
      out.write("                pg:\"kakaopay.TC0ONETIME\",\n");
      out.write("                pay_method:\"card\",\n");
      out.write("                merchant_uid:\"iamport_test_together\" + new Date().getTime(),\n");
      out.write("                name:gName,\n");
      out.write("                amount: totalPrice,\n");
      out.write("                buy_email:mEmail,\n");
      out.write("                buy_name: mName,\n");
      out.write("                buy_tel :mPhone,\n");
      out.write("                   }, async function(rsp){\n");
      out.write("                   if(rsp.success){ \n");
      out.write("                      console.log(rsp);\n");
      out.write("                      console.log(mNo);\n");
      out.write("                       var sendData = \"gNo=\"+gNo+\"&gName=\"+gName+\"&rCheckIn=\"+rCheckIn+\"&rCheckOut=\"+rCheckOut+\"&mNo=\"+mNo+\"&rPeople=\"\n");
      out.write("                       +selectItem+\"&rPrice=\"+totalPrice+\"&hNo=\"+hNo+\"&point=\"+point;\n");
      out.write("                      console.log(rCheckIn);\n");
      out.write("                       $.ajax({\n");
      out.write("                             url: \"http://localhost:8080/sevenfactory/kakaopay1\", // 예: https://www.myservice.com/payments/complete\n");
      out.write("                               method: \"POST\",\n");
      out.write("                               data: sendData,\n");
      out.write("                               success :function(rsp){\n");
      out.write("                                  console.log(\"성공\");\n");
      out.write("                               }\n");
      out.write("                           }).done(function (data) {\n");
      out.write("                             // 가맹점 서버 결제 API 성공시 로직\n");
      out.write("                              alert(\"결제가 완료되었습니다. 예약확인 페이지로 이동합니다.\");\n");
      out.write("                              window.location = 'http://localhost:8080/sevenfactory/MyReservation?mNo='+mNo;\n");
      out.write("                           });\n");
      out.write("                   }else{\n");
      out.write("                      alert(\"메시지(\"+rsp.error_msg+\")\");\n");
      out.write("                   }\n");
      out.write("             });\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("      \n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_kakaopay2(f){\n");
      out.write("      var gNo ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("      var rCheckIn ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckIn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("      var rCheckOut ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckOut }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("      var hNo ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.hNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("      if($(\"#selectPeople\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(").val() == ''){\n");
      out.write("            alert('인원을 선택해주세요.');\n");
      out.write("            return;\n");
      out.write("         }else{\n");
      out.write("            IMP.init('imp81561510');\n");
      out.write("             IMP.request_pay({\n");
      out.write("                pg:\"kakaopay.TC0ONETIME\",\n");
      out.write("                pay_method:\"card\",\n");
      out.write("                merchant_uid:\"iamport_test_together\" + new Date().getTime(),\n");
      out.write("                name:gName,\n");
      out.write("                amount: totalPrice,\n");
      out.write("                buy_name: nmName,\n");
      out.write("                   }, async function(rsp){\n");
      out.write("                   if(rsp.success){ \n");
      out.write("                      console.log(rsp);\n");
      out.write("                      console.log(hNo);\n");
      out.write("                       var sendData = \"gNo=\"+gNo+\"&gName=\"+gName+\"&rCheckIn=\"+rCheckIn+\"&rCheckOut=\"+rCheckOut+\"&rPeople=\"\n");
      out.write("                       +selectItem+\"&rPrice=\"+totalPrice+\"&hNo=\"+hNo+\"+&nmPhone=\"+nmPhone+\"&nmName=\"+nmName;\n");
      out.write("                      console.log(nmPhone);\n");
      out.write("                      console.log(nmName);\n");
      out.write("                       $.ajax({\n");
      out.write("                             url: \"http://localhost:8080/sevenfactory/kakaopay2\", \n");
      out.write("                               method: \"POST\",\n");
      out.write("                               data: sendData,\n");
      out.write("                               success :function(rsp){\n");
      out.write("                                  console.log(\"성공\");\n");
      out.write("                               }\n");
      out.write("                           }).done(function (data) {\n");
      out.write("                             // 가맹점 서버 결제 API 성공시 로직\n");
      out.write("                              alert(\"결제가 완료되었습니다. 예약확인 페이지로 이동합니다.\");\n");
      out.write("                              window.location = 'http://localhost:8080/sevenfactory/findReservationNumber'; \n");
      out.write("                           });\n");
      out.write("                   }else{\n");
      out.write("                      alert(\"메시지(\"+rsp.error_msg+\")\");\n");
      out.write("                   }\n");
      out.write("             });\n");
      out.write("        }\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   function fn_stepUp(){\n");
      out.write("      $('#step1').css('display','none');\n");
      out.write("      $('#step2').css('display','inline');\n");
      out.write("      $('#step_img').attr('src','resources/assets/reservation_img/R_STEP2.PNG')\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("</script>\n");
      out.write("<div id=\"selectedRoomContainer\" style=\"margin-top:200px\">\n");
      out.write("   <form name=\"form\" >\n");
      out.write("      <img id=\"step_img\" alt=\"step\" src=\"resources/assets/reservation_img/R_STEP1.png\" ><br/>\n");
      out.write("   <div id=\"step1\">\n");
      out.write("            <div class=\"step1_left\" >\n");
      out.write("                  <h3>약관동의</h3>\n");
      out.write("                  <div class=\"con_tit\">\n");
      out.write("                     <input type=\"checkbox\" id=\"all_agree\" />\n");
      out.write("                     <label for=\"all_agree\"><span>전체약관에 모두 동의합니다.</span></label>\n");
      out.write("                     \n");
      out.write("                     <span style=\"display: block; margin-top: 5px;\">(이용시 유의사항, 성인 확인)</span>\n");
      out.write("                  </div ><br/><br/>\n");
      out.write("                  <div class=\"con_tit\">\n");
      out.write("                     <input type=\"checkbox\" id=\"ag_use\" /><label for=\"ag_use\">이용시 유의사항에 동의</label>\n");
      out.write("                  </div>\n");
      out.write("                  <div  class=\"con_desc\">\n");
      out.write("                        <textarea cols=\"80\" rows=\"10\" readonly style=\"width: 560px; text-align: left;\">\n");
      out.write("                           1) 보호자를 동반하지 않은 미성년자는 어떠한 경우에도 입실하실 수 없습니다.\n");
      out.write("                           2) 체크아웃 준비 후 객실 점검을 위해 카운터에 말씀해 주시고 난 뒤 체크아웃 진행하도록 하겠습니다.\n");
      out.write("                           3) 퇴실 시간 초과 시 1시간당 20,000원 추가 금액 발생되는 점 양해 부탁드립니다.\n");
      out.write("                           4) 추가적인 용품 문의나 문의사항은 1층 카운터로 문의 바랍니다.(오전 9시 ~ 오후 9시)\n");
      out.write("                           5) 오후 10시 이후의 바비큐장 이용 및 고성방가는 타객실 손님을 위하여 금하오니 양해 바랍니다.\n");
      out.write("                           6) 객실 내에서는 절대 금연입니다.\n");
      out.write("                           7) 와인잔 대여를 원하시는 분들은 1층 카운터에 문의 바랍니다.\n");
      out.write("                           8) 예약하신 분 이외의 방문 및 초대를 절대 금합니다. (무단 입실 시 환불 없이 퇴실 조치 되오니 양해 바랍니다.)\n");
      out.write("                           9) 객실과 편의시설, 수영장 등 이용시설에 화재 위험이 있는 모든 종류의 화기성 물품(양초 및 폭죽, 모기향 등)의 사용을 절대 금지합니다.\n");
      out.write("                           10) 바비큐는 화재 및 냄새로 인한 타 손님의 배려 차원에서 지정된 장소에서만 이용 가능합니다. (개인 취사용 화기 사용 금지)\n");
      out.write("                           11) 바비큐 사용 시에는 객실 유리와 테라스 유리에 충분히 거리를 두신 후 사용해 주시기 바랍니다. 기온 차이로 인해 유리가 파손될 우려가 있으니 이점 꼭 유의해 주시기 바랍니다.\n");
      out.write("                           12) 복층 객실의 경우 난간이나 계단 등 안전사고에 주의하시기 바랍니다.\n");
      out.write("                           13) 싱크대 밑 수납장에 식기도구와 냄비 등 구비되어 있으니 사용하시고 음식물 쓰레기통은 싱크대 바로 밑 수납장에 있으니 분리수거와 사용하신 주방기기 및 식기류는 깨끗이 정리해주십시오.\n");
      out.write("                           14) 퇴실 시 음식물은 분리수거해주시고 모든 쓰레기는 한곳에 모아두시면 됩니다.\n");
      out.write("                           15) 객실 내 안전사고에 유의하시고, 사용 미숙과 부주의로 발생한 사고에 대해 투개더에서는 책임지지 않습니다.\n");
      out.write("                           16)객실 정리가 끝나시면 호텔 관리자에게 연락하시어 퇴실 점검을 받으시기 바랍니다.\n");
      out.write("                        </textarea>\n");
      out.write("                  </div >\n");
      out.write("                  <div class=\"con_tit\">\n");
      out.write("                        <input type=\"checkbox\" id=\"ag_adult\" />\n");
      out.write("                        <label for=\"ag_adult\">이용자가 미성년자가 아니며 성인임에 동의</label>\n");
      out.write("                  </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"step1_right\">\n");
      out.write("               \n");
      out.write("                  <h3>예약정보입력</h3>\n");
      out.write("                  <div class=\"step1_user_info\">\n");
      out.write("                              ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                              ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("   \n");
      out.write("                  </div>\n");
      out.write("                  <br/><br/>\n");
      out.write("                  <h3>동의 후 숙박정보 입력</h3>\n");
      out.write("                  <div>\n");
      out.write("                     <input type=\"button\" id=\"stepUpBtn\" value=\"동의하고 다음페이지로\"> \n");
      out.write("                  </div>\n");
      out.write("            </div>\n");
      out.write("   </div>\n");
      out.write("   <div id=\"step2\">\n");
      out.write("   <h3>선택객실목록</h3>\n");
      out.write("   <div id=\"step2-top\">\n");
      out.write("      <table id=\"selected_room\">\n");
      out.write("            <tr>\n");
      out.write("               <th>객실명</th>\n");
      out.write("               <th>이용일</th>\n");
      out.write("               <th>인원선택</th>\n");
      out.write("               <th>기본이용요금</th>\n");
      out.write("            </tr>\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"step2-bottom\">   \n");
      out.write("         <div id=\"step2-bottom-left\">\n");
      out.write("         <h3>결제 가격</h3>\n");
      out.write("            <div id=\"bill\">\n");
      out.write("                          <table id=\"bill-table\">\n");
      out.write("                             <tr>\n");
      out.write("                                <th>기본 이용 요금</th>\n");
      out.write("                                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ gDTO.gPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                                <td></td>\n");
      out.write("                             </tr>\n");
      out.write("                             ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                             <tr>\n");
      out.write("                                <th>인원 추가요금</th>\n");
      out.write("                                <td><div id=\"firstPrice\"></div></td>\n");
      out.write("                                <td><div id=\"addPrice\"></div></td>\n");
      out.write("                             </tr>\n");
      out.write("                             <tr>\n");
      out.write("                                <th>이용기간</th>\n");
      out.write("                                <td><div id=\"nights\"></div></td>\n");
      out.write("                             </tr>\n");
      out.write("                             <tr>\n");
      out.write("                                <th>총 합계 요금</th>\n");
      out.write("                                <td><div id=\"totalPrice\"></div></td>\n");
      out.write("                                <td></td>\n");
      out.write("                             </tr>\n");
      out.write("                         </table>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <div id=\"step2-bottom-right\">\n");
      out.write("         <h3>예약하기</h3>\n");
      out.write("                   <input type=\"hidden\" name=\"hNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.hNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"gNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"gName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"rPrice\" id=\"rPrice\" value=\"\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"rCheckIn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckIn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     <input type=\"hidden\" name=\"rCheckOut\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckOut }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("            \n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("      </div>\n");
      out.write("   </form>\n");
      out.write("         \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".fa-2x {\n");
      out.write("	font-size: 13px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wkmpm92bc1&submodules=geocoder\">\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("<div>\n");
      out.write("	<div class=\"footer\">\n");
      out.write("		<ul class=\"footer_menu\">\n");
      out.write("			<li>이용약관</li>\n");
      out.write("			<li>개인정보보호정책</li>\n");
      out.write("			<li>이메일 무단 수집 금지</li>\n");
      out.write("			<li>영상정보처리기기 설치 및 운영방침</li>\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f10(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		</ul>\n");
      out.write("		<ul class=\"company_info\">\n");
      out.write("			<li>우편번호 : 24901</li>\n");
      out.write("			<li>주소 : 대전광역시 서구 대덕대로 182 오라클빌딩 10층</li>\n");
      out.write("			<li>전화번호 : 02-313-7300</li>\n");
      out.write("			<li>팩스번호 : 02-313-0516</li>\n");
      out.write("			<li>이메일 : admin@sevenfactory.com</li>\n");
      out.write("		</ul>\n");
      out.write("		<ul class=\"company_info\">\n");
      out.write("			<li>사업체명 : sevenfactory</li>\n");
      out.write("			<li>대표자 : 강현 김승현 송인재 송지섭</li>\n");
      out.write("			<li>사업자등록번호 : 325-88-00678</li>\n");
      out.write("			<li>통신판매신고번호 : 2022-대전둔산-03148호</li>\n");
      out.write("		</ul>\n");
      out.write("		<p>Copyright © 2022 OsjMesiJJe inc. All rights reserved.</p>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(421,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null  }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                       <table id=\"bill-table\" >\n");
          out.write("                                          <tr>\n");
          out.write("                                             <td>예약자명</td>\n");
          out.write("                                             <td><input id=\"nmName\" type=\"text\" name=\"nmName\" /></td>\n");
          out.write("                                          </tr>\n");
          out.write("                                          <tr>\n");
          out.write("                                             <td>   연락처</td>\n");
          out.write("                                             <td>\n");
          out.write("                                                <input id=\"nmPhone\" type=\"text\" name=\"nmPhone\" placeholder=\"예)01012341234\"/><br/>\n");
          out.write("                                                <span id=\"phoneCheckResult\"></span>\n");
          out.write("                                             </td>\n");
          out.write("                                          </tr>\n");
          out.write("                                       </table>\n");
          out.write("                                       \n");
          out.write("                              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(437,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                                        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                                       ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mPhone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(459,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty gDTO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("               <tr>\n");
          out.write("                  <td>선택된 객실이 없습니다.</td>\n");
          out.write("               </tr>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(464,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty gDTO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("               <tr>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckIn }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write('~');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rCheckOut }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>\n");
          out.write("                     기준인원 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gMinPeople }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("명, 1명 추가될때마다 2만원이 가산됩니다.\n");
          out.write("                     <br/>최대 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gMaxPeople }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("명 선택 가능합니다.<br/>\n");
          out.write("                     \n");
          out.write("                        <select id=\"selectPeople\" name=\"rPeople\" onchange=\"fn_change()\">\n");
          out.write("                        <option >::인원선택::</option>\n");
          out.write("                        <option value=\"1\">1</option>\n");
          out.write("                         ");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                         ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                        ");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                        </select>\n");
          out.write("                  </td>\n");
          out.write("                  <td>\n");
          out.write("                     ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                  </td>\n");
          out.write("               </tr>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/reservation/reservationPage.jsp(475,25) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gMaxPeople eq 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                         <option value=\"2\">2</option> \n");
          out.write("                         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/reservation/reservationPage.jsp(478,25) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gMaxPeople eq 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                         <option value=\"2\">2</option> \n");
          out.write("                         <option value=\"3\">3</option> \n");
          out.write("                         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/reservation/reservationPage.jsp(482,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gDTO.gMaxPeople eq 4}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <option value=\"2\">2</option> \n");
          out.write("                         <option value=\"3\">3</option> \n");
          out.write("                        <option value=\"4\">4</option> \n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(506,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mId ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                             <tr>\n");
          out.write("                                <th>포인트사용하기</th>\n");
          out.write("                                <td><input id=\"use_point\" name=\"use_point\" type=\"text\" placeholder='사용 포인트' style=\"width:120px;\" oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"></td>\n");
          out.write("                                <td>보유 포인트:");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                             </tr>\n");
          out.write("                             ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(538,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <img src=\"resources/assets/reservation_img/kakaopay.png\" alt=\"카카오페이\" onclick=\"fn_kakaopay1(this.form)\" width=\"120px\"/>     \n");
          out.write("\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f9_reused = false;
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent(null);
      // /WEB-INF/views/reservation/reservationPage.jsp(542,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <img src=\"resources/assets/reservation_img/kakaopay.png\" alt=\"카카오페이\" onclick=\"fn_kakaopay2(this.form)\" width=\"120px\"/>\n");
          out.write("                 \n");
          out.write("                        \n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      _jspx_th_c_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f10_reused = false;
    try {
      _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f10.setParent(null);
      // /WEB-INF/views/template/footer.jsp(22,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
      if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<a id=\"loginout\" href=\"sellerLoginform\"><i\n");
          out.write("					class=\"fas fa-sign-in-alt fa-2x\">사업자LOGIN</i></a>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
      _jspx_th_c_005fif_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f10_reused);
    }
    return false;
  }
}
