/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-07 08:58:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654647991285L));
    _jspx_dependants.put("jar:file:/C:/sevenfactory/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/sevenfactory_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");

   request.setCharacterEncoding("utf-8");
   String title = request.getParameter("title");
   if(title == null || title.isEmpty()){
      title = "Welcome to the KoreaHotel";
   }
   pageContext.setAttribute("title", title);

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Inconsolata\"> \n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("<head>   \n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("   * {\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        font-family: \"Inconsolata\", sans-serif;\n");
      out.write("   }\n");
      out.write("   body {\n");
      out.write("        margin: 0;\n");
      out.write("        padding: 0;\n");
      out.write("   }\n");
      out.write("      .header-wrap {\n");
      out.write("         top: 0;\n");
      out.write("         text-align:center;\n");
      out.write("         background-color: rgba(256, 256, 256, 0.4);\n");
      out.write("         box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\n");
      out.write("         https://saeatechnote.tistory.com/entry/CSS-display-fixed-%EA%B0%80%EC%9A%B4%EB%8D%B0-%EC%A0%95%EB%A0%AC%ED%95%98%EA%B8%B0width: 1000px;\n");
      out.write("         margin: 0 auto;\n");
      out.write("         width : 1100px;\n");
      out.write("         top : 0;\n");
      out.write("         left : 0;\n");
      out.write("         right : 0;\n");
      out.write("         position: fixed;\n");
      out.write("         z-index: 10;\n");
      out.write("      }   \n");
      out.write("      .center-tab a {\n");
      out.write("         color: white;\n");
      out.write("         text-shadow: 2px 2px 2px gray;\n");
      out.write("         text-decoration: none;\n");
      out.write("         font-size: 20px;\n");
      out.write("         font-weight: bold;\n");
      out.write("         margin: 0 40px 40px 0 ;\n");
      out.write("      }\n");
      out.write("      .center-tab > a:hover {color: black;} \n");
      out.write("      .center-tab {display: inline-block; width: 100%; margin: auto; }\n");
      out.write("      .center-tab #logo {width: 200px;}\n");
      out.write("      #loginout {margin-top: 40px; margin-right: 50px;}\n");
      out.write("      #loginout:hover {color: black;}\n");
      out.write("   .main-wrap {\n");
      out.write("      z-index: 1;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   /* .footer-wrap {\n");
      out.write("         width: 100%;\n");
      out.write("        height: 200px;\n");
      out.write("        background-color: rgb(30,30,30);\n");
      out.write("        left: 0; \n");
      out.write("        bottom: 0;\n");
      out.write("   } */\n");
      out.write("   .footer {\n");
      out.write("         height: 200px;\n");
      out.write("         width:100%;\n");
      out.write("         padding:30px 0 30px 0;\n");
      out.write("         font-size:13px;\n");
      out.write("         color:white;\n");
      out.write("         background-color:rgb(30,30,30);\n");
      out.write("         bottom: 0;\n");
      out.write("      }\n");
      out.write("      .footer .footer_menu {\n");
      out.write("         margin-bottom:20px;\n");
      out.write("      }\n");
      out.write("      .footer ul {\n");
      out.write("         overflow:hidden;\n");
      out.write("         margin:0 auto;\n");
      out.write("         width:100%;\n");
      out.write("         text-align:center;\n");
      out.write("         margin-top:10px;\n");
      out.write("      }\n");
      out.write("      .footer ul li {\n");
      out.write("         display:inline;\n");
      out.write("         margin:0;\n");
      out.write("         height:10px;\n");
      out.write("      }\n");
      out.write("      .footer ul.footer_menu li {\n");
      out.write("         padding-right:15px;\n");
      out.write("      }\n");
      out.write("      .footer ul.company_info li {\n");
      out.write("         padding-right:5px;\n");
      out.write("      }\n");
      out.write("      .footer ul.footer_menu li:after {\n");
      out.write("         content:'';\n");
      out.write("         width:1px;\n");
      out.write("         height:10px;\n");
      out.write("         background:#2e2e2e;\n");
      out.write("         display:inline-block;\n");
      out.write("         margin-left:20px;\n");
      out.write("      }\n");
      out.write("      .footer ul.company_info li:after {\n");
      out.write("         content:'';\n");
      out.write("         width:1px;\n");
      out.write("         height:10px;\n");
      out.write("         background:#2e2e2e;\n");
      out.write("         display:inline-block;\n");
      out.write("         margin-left:10px;\n");
      out.write("      }\n");
      out.write("      .footer ul li:last-child:after {\n");
      out.write("         display:none;\n");
      out.write("      }\n");
      out.write("      .footer p {\n");
      out.write("         text-align:center;\n");
      out.write("         margin-top: 10px;\n");
      out.write("      }\n");
      out.write("      .footer-img{\n");
      out.write("         width: 30px;\n");
      out.write("      }\n");
      out.write("   .footer-wrap .footer-content{\n");
      out.write("      color: rgb(170,170,170);\n");
      out.write("       column-count: 2;\n");
      out.write("       column-gap: 40px;\n");
      out.write("       font-weight: 300;\n");
      out.write("       width: 900px;\n");
      out.write("        margin: auto;\n");
      out.write("        padding: 50px 0 0 0;\n");
      out.write("   }\n");
      out.write("   .footer-bottom{\n");
      out.write("      bottom: 0;\n");
      out.write("      height: 20px;\n");
      out.write("      width: 100%;\n");
      out.write("      text-align: center;\n");
      out.write("      color: rgb(220,220,220);\n");
      out.write("      background-color: rgb(60,60,60);\n");
      out.write("   }\n");
      out.write("   .dropdown {\n");
      out.write("     position: relative;\n");
      out.write("     display: inline-block;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content {\n");
      out.write("     display: none;\n");
      out.write("     position: absolute;\n");
      out.write("     background-color: rgba(0, 0, 0, 0.6);\n");
      out.write("     min-width: 130px;\n");
      out.write("     box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("     padding: 12px 16px;\n");
      out.write("     z-index: 1;\n");
      out.write("   }\n");
      out.write("   .dropdown-content a {color:white; margin: 0 20px 40px 20px ; text-shadow: 0px 0px 0px; font-weight: lighter; }\n");
      out.write("   .dropdown:hover .dropdown-content {\n");
      out.write("     display: block;\n");
      out.write("   }\n");
      out.write("   .dropdown-content a:hover {text-decoration: underline;}\n");
      out.write("   .dropdown:hover .dropdown-content {display: block; display: }\n");
      out.write("   .dropdown:hover .dropbtn {background-color: rgb(190,190,190);}\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("   .test_1{ width:100%;height: 100%;display:none;z-index:200;position:fixed;}\n");
      out.write("   .test_1.open{ display: block;}\n");
      out.write("   .test_1.open:before{content:'';width:100%;height: 100%;z-index:25;position:fixed;background:black;opacity: 0.4;top: 0;}\n");
      out.write("   .test_1 .test_2 {   \n");
      out.write("    position: fixed;\n");
      out.write("    margin: auto;\n");
      out.write("    top: 50%;\n");
      out.write("    z-index: 30;\n");
      out.write("    background: white;\n");
      out.write("    left: 50%;\n");
      out.write("    width: 450px;\n");
      out.write("    padding: 20px 45px 50px;\n");
      out.write("    height: 630px;\n");
      out.write("    margin-top: -268px;\n");
      out.write("    margin-left: -255px;}\n");
      out.write("    \n");
      out.write("    .login-box h1 { text-align: center;}\n");
      out.write("      .login-text {width: 360px;\n");
      out.write("   height: 47px;\n");
      out.write("   padding-left: 20px;\n");
      out.write("   border: 1px solid #d9d9d9;\n");
      out.write("   margin : 0 0 10px;\n");
      out.write("   font-size: 14px;}\n");
      out.write("     .find {float: right;}\n");
      out.write("      #loginButton {    border: none;\n");
      out.write("    width: 360px;\n");
      out.write("    padding: 10px 0;\n");
      out.write("    background: black;\n");
      out.write("    color: white;\n");
      out.write("    margin: 10px 0;}\n");
      out.write("    #loginButton:hover{outline : none;background: #5A5A5A;}\n");
      out.write("      #registerButton {border:none;width: 360px; padding: 10px 0;background: #E3EAF3; margin : 0 0 10px}\n");
      out.write("      #registerButton:hover {outline: none; background: #A4CAED;}\n");
      out.write("    /*    a {text-decoration: none; font-size: 0.9em; color: black;} */\n");
      out.write("       .pop-up-close{\n");
      out.write("          border:none;\n");
      out.write("         position: absolute;\n");
      out.write("       top: -20.5px;\n");
      out.write("       right: -20px;\n");
      out.write("       width: 40px;\n");
      out.write("       height: 41px;\n");
      out.write("       text-indent: -9999px;\n");
      out.write("       background-color: transparent;\n");
      out.write("       background-image: url(resources/x-button.png);\n");
      out.write("       background-repeat: no-repeat;\n");
      out.write("       background-size: 100%;\n");
      out.write("       background-position: center;\n");
      out.write("       }  \n");
      out.write("    #kakaologin{\n");
      out.write("       background-image : url(\"resources/assets/social_login/kakao_cir.png\");\n");
      out.write("        background-repeat : no-repeat;\n");
      out.write("        background-size : 100%;\n");
      out.write("        width : 100px;\n");
      out.write("        height : 100px;\n");
      out.write("       padding: 10px 0;\n");
      out.write("       margin: 10px 0;\n");
      out.write("    }  \n");
      out.write("</style>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" \n");
      out.write("   src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wkmpm92bc1&submodules=geocoder\">\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("      \n");
      out.write("        var filename;\n");
      out.write("      \n");
      out.write("      function aa(){\n");
      out.write("         //$('.test_1').css(\"display\",\"block\");\n");
      out.write("         $('.test_1').addClass('open');\n");
      out.write("         \n");
      out.write("             $.ajax({\n");
      out.write("                  url: 'getImage',\n");
      out.write("                  type: 'POST',\n");
      out.write("                  dataType: 'JSON',\n");
      out.write("                  success: function( data ) {\n");
      out.write("                    filename = data.filename;\n");
      out.write("                    $('#getchaImg').attr(\"src\",\"resources/storage/\"+filename);\n");
      out.write("                   },\n");
      out.write("                  error: function() {\n");
      out.write("                     alert('AJAX 통신이 실패했습니다1.');\n");
      out.write("                  }\n");
      out.write("               }); \n");
      out.write("      }\n");
      out.write("      \n");
      out.write("     function cc(){\n");
      out.write("             $.ajax({\n");
      out.write("                  url: 'getImage',\n");
      out.write("                  type: 'POST',\n");
      out.write("                  dataType: 'JSON',\n");
      out.write("                  success: function( data ) {\n");
      out.write("                    filename = data.filename;\n");
      out.write("                    $('#getchaImg').attr(\"src\",\"resources/storage/\"+filename);\n");
      out.write("                   },\n");
      out.write("                  error: function() {\n");
      out.write("                     alert('AJAX 통신이 실패했습니다1.');\n");
      out.write("                  }\n");
      out.write("               }); \n");
      out.write("             $('#input_key').val('');\n");
      out.write("             $('#input_key').focus();\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      function bbb(){\n");
      out.write("         $('.test_1').removeClass('open');\n");
      out.write("         //$('.test_1').css(\"display\",\"none\");\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("       $(document).ready(function(){\n");
      out.write("            \n");
      out.write("          \n");
      out.write("            // 아이디 기억하기\n");
      out.write("            var savedID = getCookie(\"savedID\");\n");
      out.write("            $('#login_mId').val(savedID);\n");
      out.write("            \n");
      out.write("            // savedID 가 있으면, 체크박스를 체크 상태로 유지\n");
      out.write("            if ( $('#login_mId').val() != '' ) {\n");
      out.write("               $('#saveIDCheck').attr('checked', true);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            // 체크박스의 상태가 변하면,\n");
      out.write("            $('#saveIDCheck').change(function(){\n");
      out.write("               // 체크되어 있다\n");
      out.write("               if ( $('#saveIDCheck').is(':checked') ) {\n");
      out.write("                  setCookie( \"savedID\", $('#login_mId').val(), 7 );  // 7일간 쿠키에 보관\n");
      out.write("               } \n");
      out.write("               // 체크해제되어 있다.\n");
      out.write("               else {\n");
      out.write("                  deleteCookie( \"savedID\" );\n");
      out.write("               }\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // 아이디를 입력할 때\n");
      out.write("            $('#login_mId').keyup(function(){\n");
      out.write("               // 체크되어 있다\n");
      out.write("               if ( $('#saveIDCheck').is(':checked') ) {\n");
      out.write("                  setCookie( \"savedID\", $('#login_mId').val(), 7 );  // 7일간 쿠키에 보관\n");
      out.write("               }\n");
      out.write("            });\n");
      out.write("         });\n");
      out.write("        \n");
      out.write("       function fn_logout(){\n");
      out.write("                location.href='logout';\n");
      out.write("            }\n");
      out.write("        \n");
      out.write("       // loginCheck로 포스트 방식으로 매핑시키고 JSON형태로 반환한다. 그리고 input_key에 input_key에 입력된 값을 전달한다.\n");
      out.write("       function fn_login(f) {\n");
      out.write("          $.ajax({\n");
      out.write("             url : 'loginCheck',\n");
      out.write("             type : 'POST',\n");
      out.write("             dataType : 'JSON',\n");
      out.write("             data : 'input_key=' + $('#input_key').val(),\n");
      out.write("          // 매개변수로 data를 넘기는 function이 성공한다면 -> 즉 통신이 된다면\n");
      out.write("             success : function(data) {\n");
      out.write("               // 만약에 data의 result 값이 true면 ajax 로그인으로 매핑을 포스트 방식을 이용하여 json으로 리턴 그리고 mId와 mPw에 값 대입\n");
      out.write("                if (data.result == true) {\n");
      out.write("                   $.ajax({\n");
      out.write("                      url : 'login',\n");
      out.write("                      type : 'POST',\n");
      out.write("                      dataType : 'JSON',\n");
      out.write("                      data : 'mId=' + $('#login_mId').val() + '&mPw='\n");
      out.write("                            + $('#login_mPw').val(),\n");
      out.write("                      success : function(data) {\n");
      out.write("                      // 만약 데이터의 결과값이 yes가 아니면 즉 no라면 \n");
      out.write("                      // 속의 if로 들어가라\n");
      out.write("                      // data-result가 만약 deleted라면 탈퇴한 회원이라는 알럿을 뛰어라\n");
      out.write("                         if (data.result != 'YES') {\n");
      out.write("                            if (data.result == 'DELETED') {\n");
      out.write("                               alert('탈퇴한 회원입니다.');\n");
      out.write("                            } \n");
      out.write("                      // 만약 탈퇴한 회원이 아니라면 아이디와 비밀번호 중 하나를 틀린거니깐 알럿을 띄우고 로그인 비밀번호와 캡차 input을 초기화 한 후 pw로 포커스를 넘긴다.\n");
      out.write("                      // 그 후에 캡차 이미지를 다시 가져온다.\n");
      out.write("                            else {\n");
      out.write("                               alert('로그인 실패 아이디와 비밀번호를 확인하세요.');\n");
      out.write("                            }\n");
      out.write("                            $('#login_mPw').val('');\n");
      out.write("                            $('#input_key').val('');\n");
      out.write("                            $('#login_mPw').focus();\n");
      out.write("                            cc();\n");
      out.write("                      // 만약 data-result가 yes라면 -> 다시 리로드해라\n");
      out.write("                         } else {\n");
      out.write("                            location.reload();\n");
      out.write("                         }\n");
      out.write("                      },\n");
      out.write("                 // 애초에 success로 못 넘어간다면 ajax 통신이 실패함을 뛰어라\n");
      out.write("                      error : function() {\n");
      out.write("                         alert('AJAX 통신이 실패했습니다.2');\n");
      out.write("                      }\n");
      out.write("                   });\n");
      out.write("                } \n");
      out.write("             // 만약에 그림의 인증번호화 입력하신 인증번호가 다르다면 -> 캡차의 틀림을 의미하고 비운 후 포커스를 맞추고 다시 불러와라\n");
      out.write("                else {\n");
      out.write("                   alert('그림의 인증번호와 입력하신 인증번호가 다릅니다.');\n");
      out.write("                   $('#input_key').val('');\n");
      out.write("                   $('#input_key').focus();\n");
      out.write("                   cc();\n");
      out.write("                }\n");
      out.write("             },\n");
      out.write("             error : function() {\n");
      out.write("                alert('AJAX 통신이 실패했습니다.2');\n");
      out.write("             }\n");
      out.write("          });\n");
      out.write("       }\n");
      out.write("         \n");
      out.write("         // 1. 쿠키 만들기\n");
      out.write("         function setCookie( cookieName, value, exdays ) {\n");
      out.write("             var exdate = new Date();\n");
      out.write("             exdate.setDate(exdate.getDate() + exdays);\n");
      out.write("             var cookieValue = escape(value) + ((exdays==null) ? \"\" : \"; expires=\" + exdate.toGMTString());\n");
      out.write("             document.cookie = cookieName + \"=\" + cookieValue;\n");
      out.write("         }\n");
      out.write("         // 2. 쿠키 삭제\n");
      out.write("         function deleteCookie( cookieName ) {\n");
      out.write("             var expireDate = new Date();\n");
      out.write("             expireDate.setDate(expireDate.getDate() - 1);\n");
      out.write("             document.cookie = cookieName + \"= \" + \"; expires=\" + expireDate.toGMTString();\n");
      out.write("         }\n");
      out.write("         // 3. 쿠키 가져오기\n");
      out.write("         function getCookie( cookieName ) {\n");
      out.write("             cookieName = cookieName + \"=\";\n");
      out.write("             var cookieData = document.cookie;\n");
      out.write("             var start = cookieData.indexOf(cookieName);\n");
      out.write("             var cookieValue = \"\";\n");
      out.write("             if ( start != -1 ){\n");
      out.write("                 start += cookieName.length;\n");
      out.write("                 var end = cookieData.indexOf(\";\", start);\n");
      out.write("                 if(end == -1) {\n");
      out.write("                     end = cookieData.length;\n");
      out.write("                 }\n");
      out.write("                 cookieValue = cookieData.substring(start, end);\n");
      out.write("             }\n");
      out.write("             return unescape(cookieValue);\n");
      out.write("         }\n");
      out.write("         \n");
      out.write("         \n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   <div class=\"header-wrap\">\n");
      out.write("         <div class=\"center-tab\">\n");
      out.write("          <a href=\"hotelInfo\" >AboutUs</a>\n");
      out.write("          <a href=\"reservation\">Reservation</a>\n");
      out.write("           <a href=\"main\"><img id=\"logo\" alt=\"logo\" src=\"resources/logo/logogo.png\"/></a>\n");
      out.write("          <div class=\"dropdown\">\n");
      out.write("                 <a >Board▼</a>\n");
      out.write("                 <div class=\"dropdown-content\">\n");
      out.write("                   <a href=\"noticeBoardListPage\">Notice</a>\n");
      out.write("                   <a href=\"qnaBoardList\">QNA</a>\n");
      out.write("                   <a href=\"ReviewBoardListPage\">Review</a>\n");
      out.write("                 </div>\n");
      out.write("           </div>\n");
      out.write("           \n");
      out.write("           ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("           ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(" \n");
      out.write("             ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" \n");
      out.write("           ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("           </div>\n");
      out.write("        \n");
      out.write("    \n");
      out.write("   </div>\n");
      out.write("   <div class=\"main-footer\">\n");
      out.write("      <div class=\"main-wrap\">\n");
      out.write("      \n");
      out.write("      <div class=\"test_1\">\n");
      out.write("        \n");
      out.write("        <div class=\"test_2\">\n");
      out.write("         <div id=\"login\" class=\"login-box\">\n");
      out.write("            <form method=\"POST\">\n");
      out.write("                     <h1 >LOGIN</h1><br/>\n");
      out.write("                      <input class=\"login-text\" id=\"login_mId\" type=\"text\" name=\"login_mId\" placeholder=\"아이디\" autofocus /><br/>\n");
      out.write("                      <input class=\"login-text\" id=\"login_mPw\" type=\"password\" name=\"login_mPw\" placeholder=\"비밀번호\"/><br/>\n");
      out.write("                      <input id=\"saveIDCheck\" type=\"checkbox\" name=\"saveIDCheck\" value=\"true\" checked />아이디 기억하기\n");
      out.write("                      \n");
      out.write("                      <img id=\"getchaImg\" src=\"\"  style=\"width: 360px; height: 120px; \"/>\n");
      out.write("                      \n");
      out.write("                      <input id=\"input_key\" type=\"text\" name=\"input_key\" style=\"margin-top: 5px;\" />\n");
      out.write("                      <a href=\"javascript:void(0);\" onclick=\"cc()\"><i class=\"fas fa-redo-alt\"></i></a><br/>\n");
      out.write("                      <input id=\"loginButton\" type=\"button\" value=\"로그인\"  onclick=\"fn_login(this.form)\" />\n");
      out.write("                      <a href=\"https://kauth.kakao.com/oauth/authorize?client_id=2ea2f188e336c19e4a984ea7365e2507&redirect_uri=http://localhost:8080/sevenfactory/login5&response_type=code\">카카오로그인</a>\n");
      out.write("                      <input id=\"registerButton\" type=\"button\" value=\"회원가입\"  onclick=\"location.href='registerPage'\" />\n");
      out.write("                      <div class=\"find\">\n");
      out.write("                      <a href=\"findIdPage\">아이디 찾기</a>&nbsp;|&nbsp; \n");
      out.write("                      <a href=\"findPwPage\">비밀번호 찾기</a><br/>\n");
      out.write("                      </div>\n");
      out.write("                      <a href=\"findReservationNumber\">비회원 예약확인</a><br/>\n");
      out.write("            </form>\n");
      out.write("         </div>\n");
      out.write("         <button class=\"pop-up-close\" onclick=\"bbb()\"></button>\n");
      out.write("        </div>\n");
      out.write("      </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/template/header.jsp(418,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \n");
          out.write("              <a href=\"registerPage\" >REGISTER</a>\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/template/header.jsp(421,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mRight eq 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("              <a href=\"adminMain\" >Member Management</a>\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/template/header.jsp(424,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO ne null and loginDTO.mRight ne 1 and loginDTO.mRight ne 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \n");
          out.write("             <a href=\"goMyPage?mNo=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO.mNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >MyPage</a>\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/template/header.jsp(427,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("           <a id=\"loginout\" href=\"javascript:void(0);\" style=\"float: right;\" onclick=\"aa()\"><i class=\"fas fa-sign-in-alt fa-2x\"></i><br/>LOGIN</a>\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/template/header.jsp(430,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDTO ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("           <a id=\"loginout\" href=\"javascript:void(0);\" style=\"float: right;\" onclick=\"fn_logout()\"><i class=\"fas fa-sign-out-alt fa-2x\"></i><br/>LOGOUT</a>\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
